Interactive mode: check if user parameters are valid before launching the scan.

diff --git a/func/01_args b/func/01_args
--- a/func/01_args
+++ b/func/01_args
@@ -13,35 +13,32 @@ read_args() {
 			$(echo ${args[${i}]}) == "--url" ]] && \
 			argument_dns=$(( i + 1 )) && \
 			dns=${args[${argument_dns}]} && \
-			inspect "--url" "${dns}"
-		#[[ $(echo ${args[${i}]} | grep -o "\.[a-z][a-z]" ) || \
-		#	$(echo ${args[${i}]} | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" ) ]] && \
-		#	dns=${args[${i}]}
+			inspect_from_args "--url" "${dns}"
 		[[ $(echo ${args[${i}]}) == "-w" || \
 			$(echo ${args[${i}]}) == "--wait" ]] && \
 			argument_request_delay=$(( i + 1 )) && \
 			request_delay=${args[${argument_request_delay}]} && \
-			inspect "--wait" "${request_delay}"
+			inspect_from_args "--wait" "${request_delay}"
 		[[ $(echo ${args[${i}]}) == "-t" || \
 			$(echo ${args[${i}]}) == "--timeout" ]] && \
 			argument_timeout=$(( i + 1 )) && \
 			timeout=${args[${argument_timeout}]} && \
-			inspect "--timeout" "${timeout}"
+			inspect_from_args "--timeout" "${timeout}"
 		[[ $(echo ${args[${i}]}) == "-b" || \
 			$(echo ${args[${i}]}) == "--break" ]] && \
 			argument_timebreak=$(( i + 1 )) && \
 			timebreak=${args[${argument_timebreak}]} && \
-			inspect "--break" "${timebreak}"
+			inspect_from_args "--break" "${timebreak}"
 		[[ $(echo ${args[${i}]}) == "-d" || \
 			$(echo ${args[${i}]}) == "--pause-for" ]] && \
 			argument_timebreak_duration=$(( i + 1 )) && \
 			timebreak_duration=${args[${argument_timebreak_duration}]} && \
-			inspect "--pause-for" "${timebreak_duration}"
+			inspect_from_args "--pause-for" "${timebreak_duration}"
 		[[ $(echo ${args[${i}]}) == "-s" || \
 			$(echo ${args[${i}]}) == "--stop" ]] && \
 			argument_stop=$(( i + 1 )) && \
 			stopping=${args[${argument_stop}]} && \
-			inspect "--stop" "${stopping}"
+			inspect_from_args "--stop" "${stopping}"
 		[[ $(echo ${args[${i}]}) == "-k" || \
 			$(echo ${args[${i}]}) == "--keep" ]] && \
 			argument_keep_expired=$(( i + 1 )) && \
@@ -56,13 +53,13 @@ read_args() {
 			range=true && \
 			argument_range_from=$(( i + 1 )) && \
 			range_from=${args[${argument_range_from}]} && \
-			inspect "--from" "${range_from}"
+			inspect_from_args "--from" "${range_from}"
 		[[ $(echo ${args[${i}]}) == "-L" ||
 			$(echo ${args[${i}]}) == "--to" ]] && \
 			range=true && \
 			argument_range_to=$(( i + 1 )) && \
 			range_to=${args[${argument_range_to}]} && \
-			inspect "--to" "${range_to}"
+			inspect_from_args "--to" "${range_to}"
 		[[ $(echo ${args[${i}]}) == "-P" ||
 			$(echo ${args[${i}]}) == "--proxy" ]] && \
 			argument_proxy_url=$(( i + 1 )) && \
@@ -84,12 +81,12 @@ read_args() {
 			set_prefix=true && \
 			argument_set_prefix=$(( i + 1 )) && \
 			prefix=${args[${argument_set_prefix}]} #&& \
-			#inspect "--prefix" "${prefix}"
+			#inspect_from_args "--prefix" "${prefix}"
 		[[ $(echo ${args[${i}]}) == "--mac-file" ]] && \
 			read_from_file=true && \
 			argument_read_from_file=$(( i + 1 )) && \
 			file_to_read_mac_from=${args[${argument_read_from_file}]} && \
-			inspect "--mac-file" "${file_to_read_mac_from}"
+			inspect_from_args "--mac-file" "${file_to_read_mac_from}"
 		#[[ $(echo ${args[${i}]}) == "--rm-checkpoint" ]] && \
 		#	echo "Remove checkpoint file for ${dns} ?" && exit 0
 		[[ $(echo ${args[${i}]}) == "-h" || $(echo ${args[${i}]}) == "--help" ]] && \
@@ -112,49 +109,70 @@ read_args() {
 	done
 }
 
-inspect() {
+inspect_from_args() {
 	case "${1}" in
-		"--url"|"-u") inspect_dns "${2}";;
-		"--wait"|"-w") inspect_float "${1}" "${2}";;
-		"--timeout"|"-t") inspect_float "${1}" "${2}";;
-		"--break"|"-b") inspect_int "${1}" "${2}";;
-		"--pause-for"|"-d") inspect_float "${1}" "${2}";;
-		"--stop"|"-s") inspect_int "${1}" "${2}";;
-		"--from"|"-F"|"--to"|"-L") inspect_mac "${2}" "args";; # is it a well formed mac
+		"--url"|"-u"|"dns") inspect_dns "${2}" "from_args";;
+		"--wait"|"-w"|"delay") inspect_float "${1}" "${2}" "from_args";;
+		"--timeout"|"-t"|"timeout") inspect_float "${1}" "${2}" "from_args";;
+		"--break"|"-b"|"break") inspect_int "${1}" "${2}" "from_args";;
+		"--pause-for"|"-d"|"break_duration") inspect_float "${1}" "${2}" "from_args";;
+		"--stop"|"-s"|"stop") inspect_int "${1}" "${2}" "from_args";;
+		"--from"|"-F"|"--to"|"-L") inspect_mac "${2}" "from_args";; # is it a well formed mac
 		#"--prefix") inspect_mac_prefix "${2}";;
-		"--mac-file") inspect_mac_file "${2}";;
-		*) echo "Something went wrong inspecting arguments.";;
+		"--mac-file") inspect_mac_file "${2}" "from_args";;
+		*) echo "${_RED}${_BOLD}Something went wrong inspecting arguments.${_RESET}";;
 	esac
 }
 
 inspect_dns() {
+	mode=$2
 	# Check if DNS is well formed URL or IP
 	if ! [[ $(echo "${1}" | grep -Eo '((https?|ftp)://)?([a-Z0-9-]+\.)?[a-Z0-9-]+\.[a-Z0-9-]+((:)[0-9]{1,5})?') == "${1}" ||
 		$(echo "${1}" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}') == "${1}" ]]; then
-		echo -e "${_RED}ERROR: invalid DNS format.${_RESET}"
-		exit 1
+		echo -e "${_RESET}${_RED}ERROR: invalid DNS format.${_RESET}"
+		if [[ "${mode}" == "from_args" ]]; then
+			exit 1
+		else
+			return 1
+		fi
 	elif [[ $(echo "${1}" | sed 's/\ //g') == "" ]]; then
-		echo -e "${_RED}ERROR: empty DNS.${_RESET}"
-		exit 1
+		echo -e "${_RESET}${_RED}ERROR: empty DNS.${_RESET}"
+		if [[ "${mode}" == "from_args" ]]; then
+			exit 1
+		else
+			return 1
+		fi
 	fi
 }
 
 inspect_float() {
+	mode=$3
 	if ! [[ $(echo "$2" | grep -Eo '([0-9]+)?(\.)?[0-9]+') == "${2}" ]]; then
-		echo -e "${_RED}ERROR: ${_YELLOW}${1}${_RESET}${_RED} takes float or integer for parameter (e.g. ${_YELLOW}${1} 1.5${_RED}).${_RESET}"
-		exit 1
-	elif [[ $(echo "${2}" | sed 's/\ //g') == "" ]]; then
-		echo -e "${_RED}ERROR: empty value for ${_YELLOW}${1}${_RED}.${_RESET}"
+		echo -e "${_RESET}${_RED}ERROR: ${_YELLOW}${1}${_RESET}${_RED} takes float or integer for parameter (e.g. ${_YELLOW}${1} 1.5${_RED}).${_RESET}"
+		if [[ "${mode}" == "from_args" ]]; then
+			exit 1
+		else
+			return 1
+		fi
+	fi
+	if [[ "${mode}" == "from_args" && $(echo "${2}" | sed 's/\ //g') == "" ]]; then
+		echo -e "${_RESET}${_RED}ERROR: empty value for ${_YELLOW}${1}${_RED}.${_RESET}"
 		exit 1
 	fi
 }
 
 inspect_int() {
+	mode=$3
 	if ! [[ $(echo "$2" | grep -Eo '[0-9]+') == "${2}" ]]; then
-		echo -e "${_RED}ERROR: ${_YELLOW}${1}${_RESET}${_RED} takes integer for parameter (e.g. ${_YELLOW}${1} 10${_RED}).${_RESET}"
-		exit 1
-	elif [[ $(echo "${2}" | sed 's/\ //g') == "" ]]; then
-		echo -e "${_RED}ERROR: empty value for ${_YELLOW}${1}${_RED}.${_RESET}"
+		echo -e "${_RESET}${_RED}ERROR: ${_YELLOW}${1}${_RESET}${_RED} takes integer for parameter (e.g. ${_YELLOW}${1} 10${_RED}).${_RESET}"
+		if [[ "${mode}" == "from_args" ]]; then
+			exit 1
+		else
+			return 1
+		fi
+	fi
+	if [[ "${mode}" == "from_args" && $(echo "${2}" | sed 's/\ //g') == "" ]]; then
+		echo -e "${_RESET}${_RED}ERROR: empty value for ${_YELLOW}${1}${_RED}.${_RESET}"
 		exit 1
 	fi
 }
@@ -164,11 +182,15 @@ inspect_mac () {
 	# If while checking USER argument : exit 1
 	# Else, if reading a MAC file : return 1 for "bad MAC"
 	if ! [[ $(echo "$1" | grep -Eo "([0-9a-fA-F]{2}[-:]){$(( (max_mac_length / 2) - 1 ))}[0-9a-fA-F]{2}") == "${1}" ]]; then
-		if [[ ${mode} == "args" ]]; then
-			echo -e "${_RED}ERROR: invalid MAC format.${_RESET}"
-			echo -e "${_RED}Please use either ${_DIM}FORMAT_1${_RESET}${_RED} or ${_DIM}FORMAT_2${_RESET}${_RED} format.${_RESET}" | \
+		if [[ ${mode} == "from_args" || ${mode} == "from_interactive" ]]; then
+			echo -e "${_RESET}${_RED}ERROR: invalid MAC format.${_RESET}"
+			echo -e "${_RESET}${_RED}Please use either ${_DIM}FORMAT_1${_RESET}${_RED} or ${_DIM}FORMAT_2${_RESET}${_RED} format.${_RESET}" | \
 				sed -r 's/FORMAT_1/XX:XX:XX:XX:XX:XX/ ; s/FORMAT_2/XX-XX-XX-XX-XX-XX/'
-			exit 1
+			if [[ "${mode}" == "from_args" ]]; then
+				exit 1
+			else
+				return 1
+			fi
 		else
 			return 1
 		fi
